FROM mcr.microsoft.com/devcontainers/javascript-node
RUN sudo apt-get update
RUN sudo apt-get -y install software-properties-common
RUN sudo apt-get -y install python3-launchpadlib
RUN sudo add-apt-repository -y ppa:swi-prolog/stable
RUN sudo apt-get -y install swi-prolog