FROM mcr.microsoft.com/devcontainers/typescript-node
RUN sudo apt-get install software-properties-common \
&& sudo add-apt-repository ppa:swi-prolog/stable \
&& sudo apt-get update \
&& sudo apt-get install swi-prolog